export interface Teacher {
  no: string;
  Aname: string;
  name: string;
  major: string;
  edu: string;
  en?: {
    Aname: string;
    name: string;
    major: string;
    edu: string;
  };
  ja?: {
    Aname: string;
    name: string;
    major: string;
    edu: string;
  };
}

export const teachersData = {
  博士: [
    {
      no: "SS01",
      Aname: "米根老师",
      name: "米根\u3000さなみ",
      major: "博士指导老师",
      edu: "东京艺术大学 | 硕士&博士 | 日本画",
      en: {
        Aname: "Dr. Komene",
        name: "Dr. Komene",
        major: "Ph.D.",
        edu: "Tokyo University of the Arts | Master & Doctor | Japanese Painting",
      },
      ja: {
        Aname: "米根先生",
        name: "米根先生",
        major: "博士",
        edu: "東京芸術大学 | 修士・博士 | 日本画",
      },
    },
    {
      no: "SS02",
      Aname: "F.S老师",
      name: "副島\u3000しのぶ",
      major: "博士指导老师",
      edu: "东京艺术大学 | 硕士&博士 | 映像研究科动画游戏专业",
      en: {
        Aname: "Dr. F.S",
        name: "Dr. F.S",
        major: "Ph.D.",
        edu: "Tokyo University of the Arts | Master & Doctor | Animation",
      },
      ja: {
        Aname: "F.S先生",
        name: "F.S先生",
        major: "博士",
        edu: "東京芸術大学 | 修士・博士 | 映像研究科アニメーション専攻",
      },
    },
    {
      no: "SS03",
      Aname: "穆老师",
      name: "穆继聪",
      major: "博士指导老师",
      edu: "中央美术学院 | 壁画 | 学士\n东京艺术大学 | 硕士&博士 | 油画",
      en: {
        Aname: "Dr. Mu",
        name: "Dr. Mu",
        major: "Ph.D.",
        edu: "Central Academy of Fine Arts | Bachelor’s Degree | Mural Art\nTokyo University of the Arts | Master & Doctor | Oil Painting",
      },
      ja: {
        Aname: "穆先生",
        name: "穆先生",
        major: "博士",
        edu: "中央美術学院 | 壁画 | 学士\n東京芸術大学 | 修士・博士 | 油画",
      },
    },
    {
      no: "SS04",
      Aname: "川端老师",
      name: "川端\u3000健太",
      major: "博士指导老师",
      edu: "东京艺术大学 | 硕士&博士 | 油画",
      en: {
        Aname: "Dr. Kawabata",
        name: "Dr. Kawabata",
        major: "Ph.D.",
        edu: "Tokyo University of the Arts | Master & Doctor | Oil Painting",
      },
      ja: {
        Aname: "川端先生",
        name: "川端先生",
        major: "博士",
        edu: "東京芸術大学 | 修士・博士 | 油画",
      },
    },
    {
      no: "SS05",
      Aname: "蔡老师",
      name: "蔡莹臻",
      major: "博士指导老师",
      edu: "东京艺术大学 | 硕士&博士 | 陶艺",
      en: {
        Aname: "Dr. Cai",
        name: "Dr. Cai",
        major: "Ph.D.",
        edu: "Tokyo University of the Arts | Master & Doctor | Ceramics",
      },
      ja: {
        Aname: "蔡先生",
        name: "蔡先生",
        major: "博士",
        edu: "東京芸術大学 | 修士・博士 | 陶芸",
      },
    },
    {
      no: "SS06",
      Aname: "钟老师",
      name: "钟雯婷",
      major: "博士指导老师",
      edu: "东京艺术大学 | 硕士&博士 | 陶艺",
      en: {
        Aname: "Dr. Zhong",
        name: "Dr. Zhong",
        major: "Ph.D.",
        edu: "Tokyo University of the Arts | Master & Doctor | Ceramics",
      },
      ja: {
        Aname: "鐘先生",
        name: "鐘先生",
        major: "博士",
        edu: "東京芸術大学 | 修士・博士 | 陶芸",
      },
    },
    {
      no: "SS07",
      Aname: "山田老师",
      name: "山田 あさお",
      major: "博士指导老师",
      edu: "东京艺术大学 | 硕士&博士 | 工艺学科 染织专业",
      en: {
        Aname: "Dr. Yamada",
        name: "Dr. Yamada",
        major: "Ph.D.",
        edu: "Tokyo University of the Arts | Master & Doctor | Crafts (Textiles & Dyeing)",
      },
      ja: {
        Aname: "山田先生",
        name: "山田先生",
        major: "博士",
        edu: "東京芸術大学 | 修士・博士 | 工芸学科 染織専攻",
      },
    },
    {
      no: "SS08",
      Aname: "N老师",
      name: "聂晶晶",
      major: "博士指导老师",
      edu: "早稻田大学大学院 | 硕士&博士 | 教育学",
      en: {
        Aname: "Dr. N",
        name: "Dr. N",
        major: "Ph.D.",
        edu: "Waseda University Graduate School | Master & Doctor | Education",
      },
      ja: {
        Aname: "N先生",
        name: "N先生",
        major: "博士",
        edu: "早稲田大学大学院 | 修士・博士 | 教育学",
      },
    },
    {
      no: "SS10",
      Aname: "黄老师",
      name: "黄阳刚",
      major: "博士指导老师",
      edu: "多摩美术大学大学院 | 环境设计 | 硕士\n千叶大学大学院 | 环境设计 | 博士",
      en: {
        Aname: "Dr. Huang",
        name: "Dr. Huang",
        major: "Ph.D.",
        edu: "Tama Art University Graduate School | Master | Environmental Design\nChiba University Graduate School | Doctor | Environmental Design",
      },
      ja: {
        Aname: "黃先生",
        name: "黃先生",
        major: "博士",
        edu: "多摩美術大学大学院 | 環境デザイン | 修士\n千葉大学大学院 | 環境デザイン | 博士",
      },
    },
    {
      no: "SS11",
      Aname: "李老师",
      name: "李子木",
      major: "博士指导老师",
      edu: "千叶大学 | 硕士&博士 | 产品设计",
      en: {
        Aname: "Dr. Li",
        name: "Dr. Li",
        major: "Ph.D.",
        edu: "Chiba University | Master & Doctor | Product Design",
      },
      ja: {
        Aname: "李先生",
        name: "李先生",
        major: "博士",
        edu: "千葉大学 | 修士・博士 | プロダクトデザイン",
      },
    },
    {
      no: "SS12",
      Aname: "肖老师",
      name: "肖光灵",
      major: "博士指导老师",
      edu: "武藏野美术大学 | 基础设计 | 硕士\n澳门科技大学 | 设计博士",
      en: {
        Aname: "Dr. Xiao",
        name: "Dr. Xiao",
        major: "Ph.D.",
        edu: "Musashino Art University | Master’s Degree | Basic Design\nMacau University of Science and Technology | Doctor | Design",
      },
      ja: {
        Aname: "肖先生",
        name: "肖先生",
        major: "博士",
        edu: "武蔵野美術大学 | 基礎デザイン | 修士\nマカオ科技大学 | デザイン博士",
      },
    },
    {
      no: "SS13",
      Aname: "马老师",
      name: "马铭涵",
      major: "博士指导老师",
      edu: "武藏野美术大学 | 硕士&博士 | 映像研究科",
      en: {
        Aname: "Dr. Ma",
        name: "Dr. Ma",
        major: "Ph.D.",
        edu: "Musashino Art University | Master & Doctor | Imaging Studies",
      },
      ja: {
        Aname: "馬先生",
        name: "馬先生",
        major: "博士",
        edu: "武蔵野美術大学 | 修士・博士 | 映像研究科",
      },
    },
    {
      no: "SS14",
      Aname: "V老师",
      name: "R．Vincent",
      major: "博士指导老师",
      edu: "多摩美术大学 | 情报设计 | 硕士\n东京艺术大学大学院 | 先端艺术 | 博士",
      en: {
        Aname: "Dr. V",
        name: "Dr. V",
        major: "Ph.D.",
        edu: "Tama Art University | Master’s Degree | Information Design\nTokyo University of the Arts Graduate School | Doctor | Advanced Art",
      },
      ja: {
        Aname: "V先生",
        name: "V先生",
        major: "博士",
        edu: "多摩美術大学 | 情報デザイン | 修士\n東京芸術大学大学院 | 先端芸術 | 博士",
      },
    },
  ],
  纯艺方向: [
    {
      no: "SS38",
      Aname: "福岛老师",
      name: "福岛恒久",
      major: "日本画及文物修复",
      edu: "东京艺术大学 | 日本画 | 学士&硕士\n日本画巨匠、东京艺术大学前校长平山郁夫的关门弟子",
      en: {
        Aname: "Mr. Fukushima",
        name: "Mr. Fukushima",
        major: "Japanese Painting and Cultural Artifact Restoration",
        edu: "Tokyo University of the Arts | Japanese Painting | Bachelor & Master\nFinal disciple of Japanese painting master and former president of Tokyo University of the Arts, Ikuo Hirayama",
      },
      ja: {
        Aname: "福島先生",
        name: "福島先生",
        major: "日本画及び文物修復",
        edu: "東京芸術大学 | 日本画 | 学士・修士\n日本画巨匠、東京芸術大学前校長 平山郁夫 の最後の弟子",
      },
    },
    {
      no: "SS39",
      Aname: "户仓老师",
      name: "户仓英雄",
      major: "日本画及文物修复",
      edu: "东京艺术大学 | 日本画 | 学士&硕士\n日本画巨匠、东京艺术大学前校长平山郁夫的关门弟子",
      en: {
        Aname: "Mr. Tokura",
        name: "Mr. Tokura",
        major: "Japanese Painting and Cultural Artifact Restoration",
        edu: "Tokyo University of the Arts | Japanese Painting | Bachelor & Master\nFinal disciple of Japanese painting master and former president of Tokyo University of the Arts, Ikuo Hirayama",
      },
      ja: {
        Aname: "戸倉先生",
        name: "戸倉先生",
        major: "日本画及び文物修復",
        edu: "東京芸術大学 | 日本画 | 学士・修士\n日本画巨匠、東京芸術大学前校長 平山郁夫 の最後の弟子",
      },
    },
    {
      no: "SS40",
      Aname: "大塚老师",
      name: "大塚あきのり",
      major: "日本画及文物修复",
      edu: "东京艺术大学 | 日本画 | 学士\n东京艺术大学大学院 | 文物修复 | 硕士",
      en: {
        Aname: "Mr. Otsuka",
        name: "Mr. Otsuka",
        major: "Japanese Painting and Cultural Artifact Restoration",
        edu: "Tokyo University of the Arts | Japanese Painting | Bachelor\nTokyo University of the Arts Graduate School | Cultural Artifact Restoration | Master",
      },
      ja: {
        Aname: "大塚先生",
        name: "大塚先生",
        major: "日本画及び文物修復",
        edu: "東京芸術大学 | 日本画 | 学士\n東京芸術大学大学院 | 文物修復 | 修士",
      },
    },
    {
      no: "SS41",
      Aname: "李老师",
      name: "李唯亲",
      major: "日本画及文物修复",
      edu: "女子美术大学大学院 | 日本画 | 学士&硕士",
      en: {
        Aname: "Ms. Li",
        name: "Ms. Li",
        major: "Japanese Painting and Cultural Artifact Restoration",
        edu: "Joshibi University of Art and Design Graduate School | Japanese Painting | Bachelor & Master",
      },
      ja: {
        Aname: "李先生",
        name: "李先生",
        major: "日本画及び文物修復",
        edu: "女子美術大学大学院 | 日本画 | 学士・修士",
      },
    },
    {
      no: "SS42",
      Aname: "袁老师",
      name: "袁玮凡",
      major: "日本画及文物修复",
      edu: "大阪艺术大学大学院 | 日本画 | 硕士",
      en: {
        Aname: "Mr. Yuan",
        name: "Mr. Yuan",
        major: "Japanese Painting and Cultural Artifact Restoration",
        edu: "Osaka University of Arts Graduate School | Japanese Painting | Master",
      },
      ja: {
        Aname: "袁先生",
        name: "袁先生",
        major: "日本画及び文物修復",
        edu: "大阪芸術大学大学院 | 日本画 | 修士",
      },
    },
    {
      no: "SS43",
      Aname: "M老师",
      name: "三田健志",
      major: "版画",
      edu: "多摩美术大学大学院 | 版画 | 学士&硕士",
      en: {
        Aname: "Mr. M",
        name: "Mr. M",
        major: "Printmaking",
        edu: "Tama Art University Graduate School | Printmaking | Bachelor & Master",
      },
      ja: {
        Aname: "三田先生",
        name: "三田先生",
        major: "版画",
        edu: "多摩美術大学大学院 | 版画 | 学士・修士",
      },
    },
    {
      no: "SS44",
      Aname: "石毛老师",
      name: "石毛健太",
      major: "版画",
      edu: "多摩美术大学 | 信息设计 | 学士\n东京艺术大学大学院 | 版画 | 硕士",
      en: {
        Aname: "Mr. Ishige",
        name: "Mr. Ishige",
        major: "Printmaking",
        edu: "Tama Art University | Information Design | Bachelor\nTokyo University of the Arts Graduate School | Printmaking | Master",
      },
      ja: {
        Aname: "石毛先生",
        name: "石毛先生",
        major: "版画",
        edu: "多摩美術大学 | 情報デザイン | 学士\n東京芸術大学大学院 | 版画 | 修士",
      },
    },
    {
      no: "SS45",
      Aname: "华老师",
      name: "华畅",
      major: "版画",
      edu: "中国美术学院 | 版画 | 学士\n多摩美术大学大学院 | 版画 | 硕士",
      en: {
        Aname: "Ms. Hua",
        name: "Ms. Hua",
        major: "Printmaking",
        edu: "China Academy of Art | Printmaking | Bachelor\nTama Art University Graduate School | Printmaking | Master",
      },
      ja: {
        Aname: "華先生",
        name: "華先生",
        major: "版画",
        edu: "中国美術学院 | 版画 | 学士\n多摩美術大学大学院 | 版画 | 修士",
      },
    },
    {
      no: "SS46",
      Aname: "吴老师",
      name: "吴康伟",
      major: "陶艺",
      edu: "武藏野美术大学大学院 | 工艺工业设计 | 陶艺 | 硕士",
      en: {
        Aname: "Mr. Wu",
        name: "Mr. Wu",
        major: "Ceramics",
        edu: "Musashino Art University Graduate School | Craft and Industrial Design (Ceramics) | Master",
      },
      ja: {
        Aname: "呉先生",
        name: "呉先生",
        major: "陶芸",
        edu: "武蔵野美術大学大学院 | 工芸工業デザイン 陶芸 | 修士",
      },
    },
    {
      no: "SS47",
      Aname: "伊藤老师",
      name: "伊藤快斗",
      major: "雕塑",
      edu: "东京艺术大学大学院 | 雕塑 | 硕士",
      en: {
        Aname: "Mr. Ito",
        name: "Mr. Ito",
        major: "Sculpture",
        edu: "Tokyo University of the Arts Graduate School | Sculpture | Master",
      },
      ja: {
        Aname: "伊藤先生",
        name: "伊藤先生",
        major: "彫刻",
        edu: "東京芸術大学大学院 | 彫刻 | 修士",
      },
    },
    {
      no: "SS58",
      Aname: "黄老师",
      name: "黄志逍",
      major: "先端艺术",
      edu: "中央美术学院 | 现代艺术 | 学士\n东京艺术大学大学院 | 先端艺术 | 硕士",
      en: {
        Aname: "Ms. Huang",
        name: "Ms. Huang",
        major: "Advanced Art",
        edu: "Central Academy of Fine Arts | Modern Art | Bachelor\nTokyo University of the Arts Graduate School | Advanced Art | Master",
      },
      ja: {
        Aname: "黄先生",
        name: "黄先生",
        major: "先端芸術",
        edu: "中央美術学院 | 現代美術 | 学士\n東京芸術大学大学院 | 先端芸術 | 修士",
      },
    },
  ],
  设计方向: [
    {
      no: "SS12",
      Aname: "肖老师",
      name: "肖光灵",
      major: "博士指导老师",
      edu: "武藏野基础设计 | 基础设计 | 修士\n澳门科技大学 | 设计博士",
      en: {
        Aname: "Dr. Xiao",
        name: "Dr. Xiao",
        major: "Ph.D.",
        edu: "Musashino Art University | Master’s Degree | Basic Design\nMacau University of Science and Technology | Doctor | Design",
      },
      ja: {
        Aname: "肖先生",
        name: "肖先生",
        major: "博士",
        edu: "武蔵野美術大学 | 基礎デザイン | 修士\nマカオ科技大学 | デザイン博士",
      },
    },
    {
      no: "SS15",
      Aname: "井上老师",
      name: "井上さりな",
      major: "平面设计 视觉传达",
      edu: "多摩美術大学 | 学士&修士 | 平面设计",
      en: {
        Aname: "Ms. Inoue",
        name: "Ms. Inoue",
        major: "Graphic Design & Visual Communication",
        edu: "Tama Art University | Bachelor & Master | Graphic Design",
      },
      ja: {
        Aname: "井上先生",
        name: "井上先生",
        major: "平面デザイン・視覚伝達",
        edu: "多摩美術大学 | 学士・修士 | グラフィックデザイン",
      },
    },
    {
      no: "SS16",
      Aname: "汤老师",
      name: "汤为",
      major: "平面设计 视觉传达",
      edu: "同济大学设计系 | 学士\n米兰理工学院&同济大学 | 服务设计 | 硕士\n武藏野美术大学大学院 | 视觉传达 | 修士",
      en: {
        Aname: "Ms. Tang",
        name: "Ms. Tang",
        major: "Graphic Design & Visual Communication",
        edu: "Tongji University, Dept. of Design | Bachelor\nPolitecnico di Milano & Tongji University | Master of Service Design\nMusashino Art University Graduate School | Visual Communication | Master",
      },
      ja: {
        Aname: "湯先生",
        name: "湯先生",
        major: "平面デザイン・視覚伝達",
        edu: "同済大学デザイン系 | 学士\nミラノ工科大学 & 同済大学 | サービスデザイン | 修士\n武蔵野美術大学大学院 | 視覚伝達 | 修士",
      },
    },
    {
      no: "SS17",
      Aname: "林老师",
      name: "林春霞",
      major: "平面设计 视觉传达",
      edu: "广州美术大学 | 视觉传达 | 学士\n东京艺术大学大学院 | 设计研究科 | 修士",
      en: {
        Aname: "Ms. Lin",
        name: "Ms. Lin",
        major: "Graphic Design & Visual Communication",
        edu: "Guangzhou Academy of Fine Arts | Bachelor in Visual Communication\nTokyo University of the Arts Graduate School | Design Studies | Master",
      },
      ja: {
        Aname: "林先生",
        name: "林先生",
        major: "平面デザイン・視覚伝達",
        edu: "広州美術学院 | 視覚伝達 | 学士\n東京芸術大学大学院 | デザイン研究科 | 修士",
      },
    },
    {
      no: "SS18",
      Aname: "刘老师",
      name: "刘承子",
      major: "平面设计 视觉传达",
      edu: "东华大学 | 视觉传达 | 学士\n武藏野美术大学大学院 | 视觉传达 | 修士",
      en: {
        Aname: "Ms. Liu",
        name: "Ms. Liu",
        major: "Graphic Design & Visual Communication",
        edu: "Donghua University | Bachelor in Visual Communication\nMusashino Art University Graduate School | Visual Communication | Master",
      },
      ja: {
        Aname: "劉先生",
        name: "劉先生",
        major: "平面デザイン・視覚伝達",
        edu: "東華大学 | 視覚伝達 | 学士\n武蔵野美術大学大学院 | 視覚伝達 | 修士",
      },
    },
    {
      no: "SS19",
      Aname: "赵老师",
      name: "赵文欣",
      major: "平面设计 视觉传达",
      edu: "多摩美术大学 | 平面设计 | 学士\n多摩美术大学大学院 | 统合设计 | 修士",
      en: {
        Aname: "Ms. Zhao",
        name: "Ms. Zhao",
        major: "Graphic Design & Visual Communication",
        edu: "Tama Art University | Bachelor in Graphic Design\nTama Art University Graduate School | Integrated Design | Master",
      },
      ja: {
        Aname: "趙先生",
        name: "趙先生",
        major: "平面デザイン・視覚伝達",
        edu: "多摩美術大学 | グラフィックデザイン | 学士\n多摩美術大学大学院 | 統合デザイン | 修士",
      },
    },
    {
      no: "SS20",
      Aname: "高桥老师",
      name: "高桥庆衣",
      major: "平面设计 视觉传达",
      edu: "东京艺术大学 | 设计科 | 学士",
      en: {
        Aname: "Ms. Takahashi",
        name: "Ms. Takahashi",
        major: "Graphic Design & Visual Communication",
        edu: "Tokyo University of the Arts | Bachelor in Design",
      },
      ja: {
        Aname: "高橋先生",
        name: "高橋先生",
        major: "平面デザイン・視覚伝達",
        edu: "東京芸術大学 | デザイン科 | 学士",
      },
    },
    {
      no: "SS27",
      Aname: "周老师",
      name: "周君仪",
      major: "产品设计",
      edu: "中国美术学院 | 产品设计 | 学士\n多摩美术大学 | 产品设计 | 修士",
      en: {
        Aname: "Ms. Zhou",
        name: "Ms. Zhou",
        major: "Product Design",
        edu: "China Academy of Art | Bachelor in Product Design\nTama Art University Graduate School | Product Design | Master",
      },
      ja: {
        Aname: "周先生",
        name: "周先生",
        major: "プロダクトデザイン",
        edu: "中国美術学院 | プロダクトデザイン | 学士\n多摩美術大学大学院 | プロダクトデザイン | 修士",
      },
    },
    {
      no: "SS28",
      Aname: "姜老师",
      name: "姜凯铧",
      major: "产品设计",
      edu: "东京造型大学 | 产品设计 | 学士\n武藏野美术大学大学院 | 工业工艺设计 | 修士",
      en: {
        Aname: "Mr. Jiang",
        name: "Mr. Jiang",
        major: "Product Design",
        edu: "Tokyo Zokei University | Bachelor in Product Design\nMusashino Art University Graduate School | Industrial Crafts Design | Master",
      },
      ja: {
        Aname: "姜先生",
        name: "姜先生",
        major: "プロダクトデザイン",
        edu: "東京造形大学 | プロダクトデザイン | 学士\n武蔵野美術大学大学院 | 工芸工業デザイン | 修士",
      },
    },
    {
      no: "SS29",
      Aname: "张老师",
      name: "张贝贝",
      major: "空间演出",
      edu: "武汉纺织学院 | 服装设计 | 学士\n武藏野美术大学大学院 | 空间演出 | 修士",
      en: {
        Aname: "Ms. Zhang",
        name: "Ms. Zhang",
        major: "Spatial Presentation",
        edu: "Wuhan Textile University | Bachelor in Fashion Design\nMusashino Art University Graduate School | Spatial Presentation | Master",
      },
      ja: {
        Aname: "張先生",
        name: "張先生",
        major: "空間演出",
        edu: "武漢紡績大学 | ファッションデザイン | 学士\n武蔵野美術大学大学院 | 空間演出 | 修士",
      },
    },
    {
      no: "SS36",
      Aname: "唐老师",
      name: "唐之聪",
      major: "环境设计/建筑",
      edu: "北京工业大学 | 环境设计 | 学士\n多摩美术大学大学院 | 环境设计 | 修士",
      en: {
        Aname: "Mr. Tang",
        name: "Mr. Tang",
        major: "Environmental Design & Architecture",
        edu: "Beijing University of Technology | Bachelor in Environmental Design\nTama Art University Graduate School | Environmental Design | Master",
      },
      ja: {
        Aname: "唐先生",
        name: "唐先生",
        major: "環境デザイン・建築",
        edu: "北京工業大学 | 環境デザイン | 学士\n多摩美術大学大学院 | 環境デザイン | 修士",
      },
    },
    {
      no: "SS37",
      Aname: "何老师",
      name: "何琛宇",
      major: "环境设计/建筑",
      edu: "中国美术学院 | 城市设计 | 学士\n武藏野美术大学大学院 | 建筑 | 修士",
      en: {
        Aname: "Mr. He",
        name: "Mr. He",
        major: "Environmental Design & Architecture",
        edu: "China Academy of Art | Bachelor in Urban Design\nMusashino Art University Graduate School | Architecture | Master",
      },
      ja: {
        Aname: "何先生",
        name: "何先生",
        major: "環境デザイン・建築",
        edu: "中国美術学院 | 都市デザイン | 学士\n武蔵野美術大学大学院 | 建築 | 修士",
      },
    },
    {
      no: "SS44",
      Aname: "石毛老师",
      name: "石毛健太",
      major: "版画",
      edu: "多摩美术大学 | 情报设计 | 学士\n东京艺术大学大学院 | 版画 | 修士",
      en: {
        Aname: "Mr. Ishige",
        name: "Mr. Ishige",
        major: "Printmaking",
        edu: "Tama Art University | Bachelor in Information Design\nTokyo University of the Arts Graduate School | Printmaking | Master",
      },
      ja: {
        Aname: "石毛先生",
        name: "石毛先生",
        major: "版画",
        edu: "多摩美術大学 | 情報デザイン | 学士\n東京芸術大学大学院 | 版画 | 修士",
      },
    },
    {
      no: "SS48",
      Aname: "史老师",
      name: "史轶凡",
      major: "服装设计 服装技术\n服装品牌运营",
      edu: "东华大学 | 服装设计 | 学士\nBFGU | 服装技术 | 修士",
      en: {
        Aname: "Mr. Shi",
        name: "Mr. Shi",
        major: "Fashion Design & Clothing Technology\nFashion Brand Operations",
        edu: "Donghua University | Bachelor in Fashion Design\nBunka Fashion Graduate University (BFGU) | Master in Clothing Technology",
      },
      ja: {
        Aname: "史先生",
        name: "史先生",
        major: "ファッションデザイン・服装技術\nファッションブランド運営",
        edu: "東華大学 | ファッションデザイン | 学士\nBFGU | ファッション技術 | 修士",
      },
    },
    {
      no: "SS54",
      Aname: "李老师",
      name: "李臻",
      major: "情报设计",
      edu: "多摩美术大学大学院 | 情报设计 | 修士",
      en: {
        Aname: "Ms. Li",
        name: "Ms. Li",
        major: "Information Design",
        edu: "Tama Art University Graduate School | Information Design | Master",
      },
      ja: {
        Aname: "李先生",
        name: "李先生",
        major: "情報デザイン",
        edu: "多摩美術大学大学院 | 情報デザイン | 修士",
      },
    },
    {
      no: "SS60",
      Aname: "张老师",
      name: "张煜人",
      major: "舞台美术",
      edu: "中国美术学院 | 建筑设计 | 学士\n多摩美术大学大学院舞台美术 | 修士",
      en: {
        Aname: "Ms. Zhang",
        name: "Ms. Zhang",
        major: "Stage Art",
        edu: "China Academy of Art | Bachelor in Architectural Design\nTama Art University Graduate School | Stage Art | Master",
      },
      ja: {
        Aname: "張先生",
        name: "張先生",
        major: "舞台美術",
        edu: "中国美術学院 | 建築設計 | 学士\n多摩美術大学大学院 | 舞台美術 | 修士",
      },
    },
  ],
  ACG数媒电影: [
    {
      no: "SS55",
      Aname: "王老师",
      name: "王逸潇",
      major: "ACG",
      edu: "多摩美术大学大学院 | 情报设计游戏方向 | 修士",
      en: {
        Aname: "Ms. Wang",
        name: "Ms. Wang",
        major: "ACG",
        edu: "Tama Art University Graduate School | Game Design in Information Design | Master",
      },
      ja: {
        Aname: "王先生",
        name: "王先生",
        major: "ACG",
        edu: "多摩美術大学大学院 | 情報デザインゲーム方向 | 修士",
      },
    },
    {
      no: "SS56",
      Aname: "陈老师",
      name: "陈乐天",
      major: "ACG",
      edu: "京都精华大学 | 角色设计 | 学士",
      en: {
        Aname: "Mr. Chen",
        name: "Mr. Chen",
        major: "ACG",
        edu: "Kyoto Seika University | Character Design | Bachelor",
      },
      ja: {
        Aname: "陳先生",
        name: "陳先生",
        major: "ACG",
        edu: "京都精華大学 | キャラクターデザイン | 学士",
      },
    },
    {
      no: "SS22",
      Aname: "何老师",
      name: "何  りさ",
      major: "插画 絵本",
      edu: "京都精华大学 | 漫画学部 | 学士\n东京艺术大学 | 设计研究科 | 插画 | 修士",
      en: {
        Aname: "Ms. He",
        name: "Ms. He",
        major: "Illustration & Picture Books",
        edu: "Kyoto Seika University | Department of Manga | Bachelor\nTokyo University of the Arts | Graduate School of Design | Illustration | Master",
      },
      ja: {
        Aname: "何先生",
        name: "何先生",
        major: "イラスト・絵本",
        edu: "京都精華大学 | 漫画学部 | 学士\n東京芸術大学 | デザイン研究科 | イラスト | 修士",
      },
    },
    {
      no: "SS14",
      Aname: "V老师",
      name: "R．Vincent",
      major: "博士指导老师",
      edu: "多摩美术大学 | 情报设计 | 修士\n东京艺术大学大学院 | 先端艺术 | 博士",
      en: {
        Aname: "Mr. V",
        name: "Mr. V",
        major: "Ph.D. Advisor",
        edu: "Tama Art University | Information Design | Master\nTokyo University of the Arts Graduate School | Advanced Arts | Doctor",
      },
      ja: {
        Aname: "V先生",
        name: "V先生",
        major: "博士指導教員",
        edu: "多摩美術大学 | 情報デザイン | 修士\n東京芸術大学大学院 | 先端芸術 | 博士",
      },
    },
    {
      no: "SS21",
      Aname: "吴老师",
      name: "吴文奕",
      major: "插画 絵本",
      edu: "山东大学 | 设计系 | 学士\n多摩美術大学大学院 | 插画 | 修士",
      en: {
        Aname: "Ms. Wu",
        name: "Ms. Wu",
        major: "Illustration & Picture Books",
        edu: "Shandong University | Department of Design | Bachelor\nTama Art University Graduate School | Illustration | Master",
      },
      ja: {
        Aname: "呉先生",
        name: "呉先生",
        major: "イラスト・絵本",
        edu: "山東大学 | デザイン学科 | 学士\n多摩美術大学大学院 | イラスト | 修士",
      },
    },
    {
      no: "SS57",
      Aname: "吴老师",
      name: "吴伊灵",
      major: "ACG",
      edu: "京都精华大学 | 卡通专业 | 学士",
      en: {
        Aname: "Ms. Wu",
        name: "Ms. Wu",
        major: "ACG",
        edu: "Kyoto Seika University | Cartoon Major | Bachelor",
      },
      ja: {
        Aname: "呉先生",
        name: "呉先生",
        major: "ACG",
        edu: "京都精華大学 | カートゥーン専攻 | 学士",
      },
    },
    {
      no: "SS23",
      Aname: "翁老师",
      name: "翁晖",
      major: "插画 絵本",
      edu: "四川美術大学 | 視覚伝達 | 学士\n女子美術大学大学院 | 治愈系 | 修士",
      en: {
        Aname: "Ms. Weng",
        name: "Ms. Weng",
        major: "Illustration & Picture Books",
        edu: "Sichuan Fine Arts Institute | Visual Communication | Bachelor\nJoshibi University of Art and Design Graduate School | Healing Arts | Master",
      },
      ja: {
        Aname: "翁先生",
        name: "翁先生",
        major: "イラスト・絵本",
        edu: "四川美術大学 | 視覚伝達 | 学士\n女子美術大学大学院 | ヒーリング系 | 修士",
      },
    },
    {
      no: "SS24",
      Aname: "王老师",
      name: "王楚涵",
      major: "插画 絵本",
      edu: "京都精华大学 | 漫画学部 | 学士\n京都精华大学大学院 | 漫画 | 修士",
      en: {
        Aname: "Ms. Wang",
        name: "Ms. Wang",
        major: "Illustration & Picture Books",
        edu: "Kyoto Seika University | Department of Manga | Bachelor\nKyoto Seika University Graduate School | Manga | Master",
      },
      ja: {
        Aname: "王先生",
        name: "王先生",
        major: "イラスト・絵本",
        edu: "京都精華大学 | 漫画学部 | 学士\n京都精華大学大学院 | 漫画 | 修士",
      },
    },
    {
      no: "SS25",
      Aname: "潘老师",
      name: "潘青阳",
      major: "动画",
      edu: "中国美术学院 | 动画学科 | 学士\n武蔵美大学院 | 映像学科动画专业 | 修士",
      en: {
        Aname: "Mr. Pan",
        name: "Mr. Pan",
        major: "Animation",
        edu: "China Academy of Art | Animation Department | Bachelor\nMusashino Art University Graduate School | Animation in Film Studies | Master",
      },
      ja: {
        Aname: "潘先生",
        name: "潘先生",
        major: "アニメーション",
        edu: "中国美術学院 | アニメーション学科 | 学士\n武蔵野美術大学大学院 | 映像学科アニメーション専攻 | 修士",
      },
    },
    {
      no: "SS26",
      Aname: "西野老师",
      name: "西野 あさき",
      major: "动画",
      edu: "多摩美術大学 | 情報设计 | 学士\n东京艺术大学大学 | 映像研究科动画专业 | 修士",
      en: {
        Aname: "Ms. Nishino",
        name: "Ms. Nishino",
        major: "Animation",
        edu: "Tama Art University | Information Design | Bachelor\nTokyo University of the Arts | Animation Studies | Master",
      },
      ja: {
        Aname: "西野先生",
        name: "西野先生",
        major: "アニメーション",
        edu: "多摩美術大学 | 情報デザイン | 学士\n東京芸術大学 | 映像研究科アニメーション専攻 | 修士",
      },
    },
    {
      no: "SS30",
      Aname: "张老师",
      name: "张涵宸",
      major: "空间演出",
      edu: "浙大宁波理工学院 | 网络新媒体 | 学士\n武藏野美术大学大学院 | 空间演出 | 修士",
      en: {
        Aname: "Ms. Zhang",
        name: "Ms. Zhang",
        major: "Spatial Presentation",
        edu: "Zhejiang University of Technology, Ningbo | New Media | Bachelor\nMusashino Art University Graduate School | Spatial Presentation | Master",
      },
      ja: {
        Aname: "張先生",
        name: "張先生",
        major: "空間演出",
        edu: "浙江大学寧波理工学院 | ネット新メディア | 学士\n武蔵野美術大学大学院 | 空間演出 | 修士",
      },
    },
    {
      no: "SS34",
      Aname: "S老师",
      name: "清水俊平",
      major: "电影方向",
      edu: "东京艺术大学大学院 | 映像研究科电影方向 | 修士\n东京艺术大学大学院 | 现役大学讲师",
      en: {
        Aname: "Mr. S",
        name: "Mr. S",
        major: "Film Studies",
        edu: "Tokyo University of the Arts Graduate School | Film Studies | Master\nTokyo University of the Arts Graduate School | Current University Lecturer",
      },
      ja: {
        Aname: "S先生",
        name: "S先生",
        major: "映画方向",
        edu: "東京芸術大学大学院 | 映像研究科映画方向 | 修士\n東京芸術大学大学院 | 現役大学講師",
      },
    },
    {
      no: "SS33",
      Aname: "殷老师",
      name: "殷莺",
      major: "写真",
      edu: "多摩美术大学大学院 | 平面设计学科写真方向 | 修士",
      en: {
        Aname: "Ms. Yin",
        name: "Ms. Yin",
        major: "Photography",
        edu: "Tama Art University Graduate School | Graphic Design in Photography | Master",
      },
      ja: {
        Aname: "殷先生",
        name: "殷先生",
        major: "写真",
        edu: "多摩美術大学大学院 | グラフィックデザイン学科写真方向 | 修士",
      },
    },
    {
      no: "SS35",
      Aname: "山下老师",
      name: "山下 征志",
      major: "电影方向",
      edu: "东京工艺大学大学院 | 电影专业 | 学士&修士\n东京工艺大学 | 现役大学老师",
      en: {
        Aname: "Ms. Yamashita",
        name: "Ms. Yamashita",
        major: "Film Studies",
        edu: "Tokyo University of the Arts Graduate School | Film Studies | Bachelor & Master\nTokyo University of the Arts | Current University Teacher",
      },
      ja: {
        Aname: "山下先生",
        name: "山下先生",
        major: "映画方向",
        edu: "東京工芸大学大学院 | 映画専攻 | 学士&修士\n東京工芸大学 | 現役大学教員",
      },
    },
    {
      no: "SS31",
      Aname: "富泽老师",
      name: "富泽 大辅",
      major: "写真",
      edu: "东京艺术大学大学院 | 先端艺术写真领域 | 学士&修士",
      en: {
        Aname: "Mr. Tomizawa",
        name: "Mr. Tomizawa",
        major: "Photography",
        edu: "Tokyo University of the Arts Graduate School | Advanced Arts in Photography | Bachelor & Master",
      },
      ja: {
        Aname: "富沢先生",
        name: "富沢先生",
        major: "写真",
        edu: "東京芸術大学大学院 | 先端芸術写真分野 | 学士&修士",
      },
    },
    {
      no: "SS32",
      Aname: "陈老师",
      name: "陈弘毅",
      major: "写真",
      edu: "武藏野美术大学大学院 | 映像写真 | 修士",
      en: {
        Aname: "Mr. Chen",
        name: "Mr. Chen",
        major: "Photography",
        edu: "Musashino Art University Graduate School | Film Photography | Master",
      },
      ja: {
        Aname: "陳先生",
        name: "陳先生",
        major: "写真",
        edu: "武蔵野美術大学大学院 | 映像写真 | 修士",
      },
    },
  ],
  文化艺术方向: [
    {
      no: "SS49",
      Aname: "张老师",
      name: "张昱媛",
      major: "服装设计 服装技术\n服装品牌运营",
      edu: "BFGU | 服装品牌运营 | 修士",
      en: {
        Aname: "Ms. Zhang",
        name: "Ms. Zhang",
        major: "Fashion Design & Clothing Technology\nFashion Brand Operations",
        edu: "Bunka Fashion Graduate University (BFGU) | Master in Fashion Brand Operations",
      },
      ja: {
        Aname: "張先生",
        name: "張先生",
        major: "ファッションデザイン・服装技術\nファッションブランド運営",
        edu: "BFGU | ファッションブランド運営 | 修士",
      },
    },
    {
      no: "SS50",
      Aname: "张老师",
      name: "张敏乐",
      major: "美术教育",
      edu: "筑波大学大学院艺术教育 | 修士",
      en: {
        Aname: "Ms. Zhang",
        name: "Ms. Zhang",
        major: "Art Education",
        edu: "Tsukuba University Graduate School | Master in Art Education",
      },
      ja: {
        Aname: "張先生",
        name: "張先生",
        major: "美術教育",
        edu: "筑波大学大学院芸術教育 | 修士",
      },
    },
    {
      no: "SS51",
      Aname: "H老师",
      name: "侯米兰",
      major: "艺术文化 艺术学 艺术史",
      edu: "武藏野美术大学大学院 | 艺术文化 | 修士",
      en: {
        Aname: "Ms. H",
        name: "Ms. H",
        major: "Art Culture, Art Studies & Art History",
        edu: "Musashino Art University Graduate School | Art Culture | Master",
      },
      ja: {
        Aname: "H先生",
        name: "H先生",
        major: "芸術文化・芸術学・芸術史",
        edu: "武蔵野美術大学大学院 | 芸術文化 | 修士",
      },
    },
    {
      no: "SS52",
      Aname: "葛老师",
      name: "葛毓楠",
      major: "创造构想 KMD",
      edu: "青山学院大学 | 综合文化政策学科 | 学士\n武藏野美术大学大学院 | 创造构想 | 修士",
      en: {
        Aname: "Ms. Ge",
        name: "Ms. Ge",
        major: "Creative Concept & KMD",
        edu: "Aoyama Gakuin University | Department of Integrated Cultural Policy | Bachelor\nMusashino Art University Graduate School | Creative Concept | Master",
      },
      ja: {
        Aname: "葛先生",
        name: "葛先生",
        major: "創造構想・KMD",
        edu: "青山学院大学 | 総合文化政策学科 | 学士\n武蔵野美術大学大学院 | 創造構想 | 修士",
      },
    },
    {
      no: "SS53",
      Aname: "江老师",
      name: "江丹玥",
      major: "创造构想 KMD",
      edu: "庆应义塾大学大学院 | KMD | 修士",
      en: {
        Aname: "Ms. Jiang",
        name: "Ms. Jiang",
        major: "Creative Concept & KMD",
        edu: "Keio University Graduate School | KMD | Master",
      },
      ja: {
        Aname: "江先生",
        name: "江先生",
        major: "創造構想・KMD",
        edu: "慶應義塾大学大学院 | KMD | 修士",
      },
    },
    {
      no: "SS59",
      Aname: "王老师",
      name: "王昱琪",
      major: "GAP",
      edu: "纽约视觉传达学院 | 现代艺术 | 学士\n东京艺术大学大学院 | GAP | 修士",
      en: {
        Aname: "Mr. Wang",
        name: "Mr. Wang",
        major: "GAP",
        edu: "School of Visual Arts, New York | Modern Art | Bachelor\nTokyo University of the Arts Graduate School | GAP | Master",
      },
      ja: {
        Aname: "王先生",
        name: "王先生",
        major: "GAP",
        edu: "ニューヨーク視覚伝達学院 | 現代アート | 学士\n東京芸術大学大学院 | GAP | 修士",
      },
    },
  ],
};
